# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

em <- function(param2, xvec, yvec, freq, n, se, maxiter, tol, showFlag, bnb) {
    .Call('_bzinb_em', PACKAGE = 'bzinb', param2, xvec, yvec, freq, n, se, maxiter, tol, showFlag, bnb)
}

dBvZINB_Expt <- function(x, y, freq, a0, a1, a2, b1, b2, p1, p2, p3, p4, expt, s_i, info, se, bnb) {
    invisible(.Call('_bzinb_dBvZINB_Expt', PACKAGE = 'bzinb', x, y, freq, a0, a1, a2, b1, b2, p1, p2, p3, p4, expt, s_i, info, se, bnb))
}

dBvZINB_Expt_vec <- function(xvec, yvec, freq, n, a0, a1, a2, b1, b2, p1, p2, p3, p4, expt, s_i, info, se, bnb) {
    invisible(.Call('_bzinb_dBvZINB_Expt_vec', PACKAGE = 'bzinb', xvec, yvec, freq, n, a0, a1, a2, b1, b2, p1, p2, p3, p4, expt, s_i, info, se, bnb))
}

inv_digamma <- function(x, y) {
    .Call('_bzinb_inv_digamma', PACKAGE = 'bzinb', x, y)
}

